use crate::ranfile::types::{RanTarget, Ranfile};
use anyhow::{Context, Result};
use colored::Colorize;
use std::collections::HashSet;
use std::path::Path;

/// Target names reserved for `ran` subcommands — cannot be used in NTCRANFILE.
pub(crate) const RESERVED_TARGET_NAMES: &[&str] = &["init", "deinit", "help", "list", "ls"];

/// Name of the ranfile.
pub(crate) const RANFILE_NAME: &str = "NTCRANFILE.toml";

/// Default ranfile template generated by `ran init`.
pub(crate) const RANFILE_TEMPLATE: &str = r##"# NTCRANFILE — ntc task runner configuration
# Usage:
#   ran            → runs [targets.standalone]
#   ran <name>    → runs a specific target
#   ran list      → lists all targets
#   ran init      → creates this file
#   ran help    → shows full usage with examples

# ── Variables ──────────────────────────────────────────────────────────
# Define variables here and reference them with $(VAR_NAME) in commands.
#
# Example:
#   CC     = "gcc"
#   FLAGS  = "-Wall -O2"
#   OUTDIR = "dist"
#
# Then use them: cmd = "$(CC) $(FLAGS) main.c -o $(OUTDIR)/app"

[vars]
# CC = "gcc"
# FLAGS = "-O2"

# ── Targets ────────────────────────────────────────────────────────────
# Each target can have:
#   deps — list of other targets that must run first
#   cmd  — shell command to execute (goes through ntc's alias system, so
#          run aliases, @teleports, and system commands all work)

[targets]

[targets.standalone]
# Default target — runs when `ran` is typed without arguments
deps = []
cmd = "echo 'Hello from ran!'"

# [targets.build]
# deps = ["lint"]
# cmd = "echo Building..."

# [targets.lint]
# deps = []
# cmd = "ruff check ."

# [targets.test]
# deps = ["build"]
# cmd = "echo Running tests..."

# [targets.clean]
# deps = []
# cmd = "rm -rf *.o dist/"
"##;

/// Parse an NTCRANFILE.toml at the given directory.
pub(crate) fn parse(path: &Path) -> Result<Ranfile> {
    let ranfile_path = path.join(RANFILE_NAME);
    let content = std::fs::read_to_string(&ranfile_path)
        .with_context(|| format!("No {} found in {}", RANFILE_NAME, path.display()))?;
    let ranfile: Ranfile =
        toml::from_str(&content).with_context(|| format!("Failed to parse {}", RANFILE_NAME))?;

    // Validate: at least one target
    if ranfile.targets.is_empty() {
        anyhow::bail!("{} contains no [targets] section", RANFILE_NAME);
    }

    // Validate: no reserved names
    for name in ranfile.targets.keys() {
        if RESERVED_TARGET_NAMES.contains(&name.as_str()) {
            anyhow::bail!(
                "'{}' is a reserved name and cannot be used as a target in {}",
                name,
                RANFILE_NAME
            );
        }
    }

    // Validate all referenced dependencies exist
    for (name, target) in &ranfile.targets {
        for dep in &target.deps {
            if !ranfile.targets.contains_key(dep) {
                anyhow::bail!(
                    "Target '{}' depends on '{}' but '{}' is not defined in {}",
                    name, dep, dep, RANFILE_NAME
                );
            }
        }
    }

    // Check for circular dependencies
    for name in ranfile.targets.keys() {
        let mut visited = HashSet::new();
        if detect_cycle(name, &ranfile.targets, &mut visited) {
            anyhow::bail!("Circular dependency detected involving target '{}'", name);
        }
    }

    Ok(ranfile)
}

/// Check whether a dependency cycle exists starting from `target`.
fn detect_cycle(
    target: &str,
    targets: &std::collections::HashMap<String, RanTarget>,
    visited: &mut HashSet<String>,
) -> bool {
    if !visited.insert(target.to_string()) {
        return true;
    }
    if let Some(t) = targets.get(target) {
        for dep in &t.deps {
            if detect_cycle(dep, targets, visited) {
                return true;
            }
        }
    }
    visited.remove(target);
    false
}

/// Print a friendly list of all targets and their dependencies.
pub(crate) fn list_targets(ranfile: &Ranfile) {
    let mut names: Vec<&String> = ranfile.targets.keys().collect();
    names.sort();

    println!("{}", "Available targets:".cyan().bold());
    println!();
    for name in names {
        let target = &ranfile.targets[name];
        let has_cmd = if target.cmd.is_empty() { "" } else { " (has command)" };
        let dep_str = if target.deps.is_empty() {
            String::new()
        } else {
            format!(" ─▶ depends on: {}", target.deps.join(", "))
        };
        println!("  {}{}{}", name.green(), dep_str.yellow(), has_cmd.dimmed());
    }
}
