#[allow(dead_code)]
pub struct TutorialStep {
    pub id: &'static str,
    pub title: &'static str,
    pub lines: &'static [&'static str],
    pub demo: Option<&'static str>,
    pub try_it: Option<&'static str>,
}

pub const STEPS: &[TutorialStep] = &[
    TutorialStep {
        id: "welcome",
        title: "Welcome to NTC",
        lines: &[
            "NTC (Navigate, Toolkit, Center) is a modern command-line tool for",
            "file management, navigation, searching, reports, and text editing.",
            "",
            "This tutorial will walk you through the key features step by step.",
            "You'll learn how to navigate, search, generate reports, edit files,",
            "customize themes, manage backups, and more.",
            "",
            "Each step explains a feature, sometimes with a live demo.",
            "Just press Enter to advance through the tutorial.",
        ],
        demo: None,
        try_it: Some("Type \'help\' at any time to see all available commands"),
    },
    TutorialStep {
        id: "navigation",
        title: "Navigation",
        lines: &[
            "NTC organizes your filesystem as an interactive directory tree.",
            "You can move around and inspect your project structure easily:",
            "",
            "  go <path>      — Navigate to a directory and show its tree",
            "  cd <path>      — Same as go",
            "  back           — Return to the previous directory",
            "  where          — Print your current directory path",
            "  gos            — List subdirectories and pick one",
            "  godrive        — Browse Windows drives (Windows only)",
        ],
        demo: Some("where"),
        try_it: Some("Try: go ..  to go up one level"),
    },
    TutorialStep {
        id: "search",
        title: "Searching Files and Directories",
        lines: &[
            "Quickly find files and directories by name or pattern:",
            "",
            "  fs <pattern>   — Find files matching a pattern",
            "  ds <pattern>   — Find directories matching a pattern",
            "  locate <name>  — Find a file or directory anywhere",
            "  fgo <pattern>  — Fuzzy-find then navigate to a directory",
            "",
            "Search respects your ignored directories (like target/, .git/).",
            "You can also use -d <depth> to limit search depth.",
        ],
        demo: None,
        try_it: Some("Try: fs *.rs   (or any pattern you like)"),
    },
    TutorialStep {
        id: "reports",
        title: "Project Reports",
        lines: &[
            "Generate reports of your project structure and content:",
            "",
            "  txt            — Generate a text report",
            "  html           — Generate an HTML report",
            "  json           — Generate a JSON report",
            "  md             — Generate a Markdown report",
            "  view           — Preview the report in your terminal",
            "",
            "Reports include the directory tree and file contents.",
            "Use -d <depth> to control how deep the tree goes.",
        ],
        demo: Some("txt -d 1"),
        try_it: Some("Try: txt -d 2  for a deeper report"),
    },
    TutorialStep {
        id: "file-ops",
        title: "File Operations",
        lines: &[
            "Create and manage files and directories:",
            "",
            "  mkf <file>     — Create a new file",
            "  mkd <dir>      — Create a new directory",
            "  rmf <file>     — Delete a file (with confirmation)",
            "  rmd <dir>      — Delete a directory (with confirmation)",
            "  cp <src> <dst> — Copy a file",
            "",
            "All destructive commands prompt for confirmation.",
        ],
        demo: None,
        try_it: Some("Try: mkd test_dir  to create a directory"),
    },
    TutorialStep {
        id: "editor",
        title: "Built-in Text Editor",
        lines: &[
            "NTC includes a full-featured terminal text editor:",
            "",
            "  ne <file>      — Open a file in the editor",
            "  ne --init <f>  — Create a file from a template",
            "  ne .           — Open scratch buffer (unnamed file)",
            "",
            "Editor modes:",
            "  Normal mode (default) — navigate with h/j/k/l or arrows",
            "  Insert mode  — press i to enter, Esc to exit",
            "  Command mode — press : then type w (save), q (quit), wq",
            "  Search mode  — press / then type your query",
        ],
        demo: None,
        try_it: Some("Try: ne myfile.txt  then press i to type, Esc, :wq to save & quit"),
    },
    TutorialStep {
        id: "themes",
        title: "Themes",
        lines: &[
            "Customize the look and feel of NTC:",
            "",
            "  theme               — Interactive theme picker",
            "  theme list          — List all available themes",
            "  theme <name>        — Switch to a theme",
            "  theme add <name>    — Create a new theme (opens in editor)",
            "  theme rm <name>     — Delete a custom theme",
            "",
            "Themes control syntax highlighting, shell UI, and editor colors.",
            "Theme files use TOML format and live in your config directory.",
        ],
        demo: Some("theme list"),
        try_it: Some("Try: theme default  or  theme light"),
    },
    TutorialStep {
        id: "backups",
        title: "Backups",
        lines: &[
            "Protect your work with the built-in backup system:",
            "",
            "  bkup            — Create a backup of the current project",
            "  pldw <n>        — Restore a backup by number",
            "  unpd            — Undo the last restore",
            "  diff <n>        — Compare current state with a backup",
            "  bkup clear      — Remove all backups for this project",
            "",
            "Backups are stored in your NTC config directory.",
        ],
        demo: None,
        try_it: Some("Try: bkup  to create your first backup"),
    },
    TutorialStep {
        id: "configuration",
        title: "Configuration",
        lines: &[
            "Configure NTC to match your workflow:",
            "",
            "  setO <path>     — Set default output path for reports",
            "  setD <int>      — Set maximum directory tree depth (1-20)",
            "  setL ON|OFF     — Toggle line numbers in reports",
            "  setT <int>      — Set number of search threads",
            "  setC ON|OFF     — Toggle color output",
            "  watch ON|OFF    — Enable live file watching",
            "  showcg          — Display current configuration",
            "  opencg          — Edit config file directly",
        ],
        demo: Some("showcg"),
        try_it: Some("Try: setD 3  to change tree depth to 3"),
    },
    TutorialStep {
        id: "teleports",
        title: "Teleport Shortcuts",
        lines: &[
            "Create shortcuts to frequently used directories:",
            "",
            "  tp-add <name> <path>   — Save a teleport shortcut",
            "  tp-list                — List all teleports",
            "  tp-rm <name>           — Remove a teleport",
            "  @<name>                — Jump instantly to a teleport",
            "",
            "Teleports are persistent across sessions and make",
            "navigation between projects lightning-fast.",
        ],
        demo: Some("tp list"),
        try_it: Some("Try: tp add work C:\\Users\\YourName\\Projects\\work"),
    },
    TutorialStep {
        id: "aliases",
        title: "Aliases",
        lines: &[
            "Create command shortcuts and custom commands:",
            "",
            "  ral add <name> <cmd>   — Create a new alias",
            "  ral list               — List all aliases",
            "  ral edit <name>        — Edit an alias in the editor",
            "  ral rm <name>          — Remove an alias",
            "  run <name> [args]      — Run an alias with arguments",
            "",
            "Aliases can use variables ($name, ${name}) and arguments.",
            "They support chaining with && for multi-step commands.",
        ],
        demo: Some("ral list"),
        try_it: Some("Try: ral add ll go .  then type ll to test it"),
    },
    TutorialStep {
        id: "completion",
        title: "You're All Set!",
        lines: &[
            "You've completed the NTC tutorial. Here's a quick recap:",
            "",
            "  Navigation  — go, cd, back, where",
            "  Search      — fs, ds, locate, fgo",
            "  Reports     — txt, html, json, md",
            "  File Ops    — mkf, mkd, rmf, rmd",
            "  Editor      — ne (built-in terminal editor)",
            "  Themes      — theme list, theme <name>",
            "  Backups     — bkup, pldw, unpd, diff",
            "  Config      — setO, setD, showcg, watch",
            "  Teleports   — tp-add, tp-list, @shortcut",
            "  Aliases     — ral add, ral list, run",
            "",
            "Type 'help' for the full command reference.",
            "Type 'exit' or press Ctrl+C to quit NTC.",
        ],
        demo: None,
        try_it: None,
    },
];
