
# Create it fresh with UTF-8
max_depth = 1
show_line_numbers = true
num_threads = 16

ignored_directory_names = [
    "target",
    "build",
    "venv",
    "node_modules",
    "installer",
    ".git",
    "test"
]

ignored_extensions = ["lock", "log"]
extra_supported_extensions = ["lock"]
ignored_files = ["Cargo.lock"]

history_enabled = true

