use crate::config::Config;
use crate::explorer::{generate_tree, TreeNode};
use crate::filetype::FormatConfig;
use anyhow::Result;
use std::path::{Path, PathBuf};
use std::time::Instant;

pub struct MarkdownReportGenerator;

impl MarkdownReportGenerator {
    pub fn generate(dir_path: &Path, output_path: &Path, depth: Option<usize>) -> Result<()> {
        let start = Instant::now();
        let dir_name = dir_path.file_name().unwrap_or_default().to_string_lossy();
        
        eprintln!("📊 Generating Markdown report for: {}", dir_name);
        
        // Generate tree
        let tree = generate_tree(
            dir_path.to_string_lossy().as_ref(),
            depth,
            true,
            None,
        );
        
        let content = build_markdown_content(&tree, dir_path, start.elapsed().as_secs_f64())?;
        
        std::fs::write(output_path, content)?;
        
        eprintln!("✅ Markdown report saved to: {}", output_path.display());
        
        Ok(())
    }
    
    pub fn generate_to_string(dir_path: &Path, depth: Option<usize>) -> Result<String> {
        let start = Instant::now();
        let tree = generate_tree(
            dir_path.to_string_lossy().as_ref(),
            depth,
            true,
            None,
        );
        
        build_markdown_content(&tree, dir_path, start.elapsed().as_secs_f64())
    }
}

fn build_markdown_content(tree: &TreeNode, dir_path: &Path, scan_time: f64) -> Result<String> {
    let fmt_cfg = FormatConfig::from_global();
    let (supported_files, unsupported_files) = collect_files(dir_path, &fmt_cfg)?;
    let total_size = crate::explorer::calculate_total_size(dir_path);
    
    let mut content = String::new();
    
    // Header
    content.push_str(&format!("# 📁 {} Directory Report\n\n", tree.name));
    content.push_str("> Generated by [ntc](https://github.com/NuengCoder/ntc)\n\n");
    content.push_str(&format!("**Path:** `{}`  \n", dir_path.display()));
    content.push_str(&format!("**Date:** {}  \n", chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));
    content.push_str(&format!("**Scan Time:** {:.2} seconds\n\n", scan_time));
    
    // Statistics Table
    content.push_str("## 📊 Statistics\n\n");
    content.push_str("| Metric | Value |\n");
    content.push_str("|--------|-------|\n");
    content.push_str(&format!("| Total Files | {} |\n", count_files(tree)));
    content.push_str(&format!("| Total Directories | {} |\n", count_dirs(tree)));
    content.push_str(&format!("| Total Size | {} |\n", crate::explorer::human_readable_size(total_size)));
    content.push_str(&format!("| Supported Files | {} |\n", supported_files.len()));
    content.push_str(&format!("| Unsupported Files | {} |\n\n", unsupported_files.len()));
    
    // Configuration
    content.push_str("## ⚙️ Configuration\n\n");
    content.push_str("```toml\n");
    content.push_str(&format!("max_depth = {}\n", Config::global_get_max_depth()));
    content.push_str(&format!("show_line_numbers = {}\n", Config::global_get_show_line_numbers()));
    content.push_str("```\n\n");
    
    // Directory Tree
    content.push_str("## 🌳 Directory Tree\n\n");
    content.push_str("```\n");
    content.push_str(&format_tree_md(tree, "", true));
    content.push_str("```\n\n");
    
    // Supported Files
    content.push_str("## 📄 Supported Files\n\n");
    for file_path in &supported_files {
        let file_name = file_path.file_name().unwrap_or_default().to_string_lossy();
        content.push_str(&format!("### `{}`\n\n", file_name));
        
        if let Ok(file_content) = crate::output::cat_file_with_line_numbers(file_path, Config::global_get_show_line_numbers()) {
            content.push_str("```\n");
            content.push_str(&file_content);
            content.push_str("```\n\n");
        } else {
            content.push_str("*[Error reading file]*\n\n");
        }
    }
    
    // Unsupported Files
    if !unsupported_files.is_empty() {
        content.push_str("## ⚠️ Skipped Files (Unsupported Format)\n\n");
        for file_path in &unsupported_files {
            let file_name = file_path.file_name().unwrap_or_default().to_string_lossy();
            content.push_str(&format!("- `{}`\n", file_name));
        }
        content.push('\n');
    }
    
    // Footer
    content.push_str("---\n");
    content.push_str(&format!("*Report generated by ntc v{}*\n", env!("CARGO_PKG_VERSION")));
    
    Ok(content)
}

fn format_tree_md(node: &TreeNode, prefix: &str, is_last: bool) -> String {
    let mut output = String::new();
    
    let connector = match node.depth {
        0 => "",
        _ if is_last => "└── ",
        _ => "├── ",
    };
    
    let suffix = if node.is_dir && node.depth > 0 {
        if let Some(size) = node.size {
            format!(" [Directory] ({})", crate::explorer::human_readable_size(size))
        } else {
            " [Directory]".to_string()
        }
    } else {
        String::new()
    };
    
    output.push_str(&format!("{}{}{}{}\n", prefix, connector, node.name, suffix));
    
    for (i, child) in node.children.iter().enumerate() {
        let is_last_child = i == node.children.len() - 1;
        let new_prefix = match node.depth {
            0 => String::new(),
            _ if is_last => format!("{}    ", prefix),
            _ => format!("{}│   ", prefix),
        };
        output.push_str(&format_tree_md(child, &new_prefix, is_last_child));
    }
    
    output
}

fn collect_files(dir_path: &Path, _fmt_cfg: &FormatConfig) -> Result<(Vec<PathBuf>, Vec<PathBuf>)> {
    let max_depth = Config::global_get_max_depth();
    Ok(super::collect_report_files(dir_path, max_depth))
}

fn count_files(node: &TreeNode) -> u64 {
    let mut count = if !node.is_dir { 1 } else { 0 };
    for child in &node.children {
        count += count_files(child);
    }
    count
}

fn count_dirs(node: &TreeNode) -> u64 {
    let mut count = if node.is_dir && node.depth > 0 { 1 } else { 0 };
    for child in &node.children {
        count += count_dirs(child);
    }
    count
}

