use crossterm::style::Color;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenType {
    Normal,
    Keyword,
    String,
    Comment,
    Number,
    Type,
    Builtin,
    Function,
    Operator,
    Punctuation,
    Attribute,
    Macro,
    Regex,
    Tag,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub start: usize,
    pub end: usize,
    pub token_type: TokenType,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyntaxLanguage {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    Go,
    C,
    Cpp,
    CSharp,
    Java,
    Kotlin,
    Swift,
    Dart,
    Ruby,
    Bash,
    Lua,
    Php,
    Perl,
    Haskell,
    Elixir,
    Zig,
    Nim,
    Scala,
    Clojure,
    OCaml,
    R,
    Julia,
    Erlang,
    Xml,
    Yaml,
    Pro,
    Html,
    Json,
    Markdown,
    Txt,
    GoMod,
    GoSum,
    Dotenv,
    Css,
    Bat,
    Ps1,
}

pub fn color_for(tt: TokenType) -> Color {
    match tt {
        TokenType::Keyword => Color::Rgb { r: 200, g: 160, b: 255 },
        TokenType::String => Color::Rgb { r: 103, g: 228, b: 128 },
        TokenType::Comment => Color::Rgb { r: 108, g: 108, b: 128 },
        TokenType::Number => Color::Rgb { r: 255, g: 202, b: 133 },
        TokenType::Type => Color::Rgb { r: 120, g: 220, b: 232 },
        TokenType::Builtin => Color::Rgb { r: 255, g: 140, b: 154 },
        TokenType::Function => Color::Rgb { r: 130, g: 226, b: 255 },
        TokenType::Operator => Color::Rgb { r: 200, g: 200, b: 208 },
        TokenType::Punctuation => Color::Rgb { r: 132, g: 132, b: 154 },
        TokenType::Attribute => Color::Rgb { r: 162, g: 119, b: 255 },
        TokenType::Macro => Color::Rgb { r: 176, g: 131, b: 240 },
        TokenType::Regex => Color::Rgb { r: 252, g: 169, b: 110 },
        TokenType::Tag => Color::Rgb { r: 80, g: 228, b: 200 },
        TokenType::Normal => Color::Rgb { r: 200, g: 200, b: 208 },
    }
}

pub fn detect_language(ext: &str) -> Option<SyntaxLanguage> {
    match ext.to_lowercase().as_str() {
        "rs" => Some(SyntaxLanguage::Rust),
        "py" | "pyw" | "pyx" => Some(SyntaxLanguage::Python),
        "js" | "mjs" | "cjs" => Some(SyntaxLanguage::JavaScript),
        "ts" | "tsx" | "mts" | "cts" => Some(SyntaxLanguage::TypeScript),
        "go" => Some(SyntaxLanguage::Go),
        "c" | "h" => Some(SyntaxLanguage::C),
        "cpp" | "cc" | "cxx" | "c++" | "hpp" | "hh" | "hxx" => Some(SyntaxLanguage::Cpp),
        "cs" | "csx" => Some(SyntaxLanguage::CSharp),
        "java" | "jsp" | "jspx" | "tag" => Some(SyntaxLanguage::Java),
        "kt" | "kts" | "ktm" => Some(SyntaxLanguage::Kotlin),
        "swift" => Some(SyntaxLanguage::Swift),
        "dart" => Some(SyntaxLanguage::Dart),
        "rb" | "rbw" | "gemspec" => Some(SyntaxLanguage::Ruby),
        "sh" | "bash" | "zsh" | "ksh" | "fish" => Some(SyntaxLanguage::Bash),
        "lua" => Some(SyntaxLanguage::Lua),
        "php" | "phtml" | "php3" | "php4" | "php5" | "php7" | "phps" => Some(SyntaxLanguage::Php),
        "pl" | "pm" | "t" => Some(SyntaxLanguage::Perl),
        "hs" | "lhs" => Some(SyntaxLanguage::Haskell),
        "ex" | "exs" => Some(SyntaxLanguage::Elixir),
        "zig" => Some(SyntaxLanguage::Zig),
        "nim" => Some(SyntaxLanguage::Nim),
        "scala" | "sc" => Some(SyntaxLanguage::Scala),
        "clj" | "cljs" | "cljc" | "edn" => Some(SyntaxLanguage::Clojure),
        "ml" | "mli" => Some(SyntaxLanguage::OCaml),
        "r" | "R" | "rmd" => Some(SyntaxLanguage::R),
        "jl" => Some(SyntaxLanguage::Julia),
        "erl" | "hrl" => Some(SyntaxLanguage::Erlang),
        "xml" | "xsd" | "xsl" | "xslt" | "svg" | "plist" => Some(SyntaxLanguage::Xml),
        "yml" | "yaml" => Some(SyntaxLanguage::Yaml),
        "pro" => Some(SyntaxLanguage::Pro),
        "html" | "htm" | "xhtml" => Some(SyntaxLanguage::Html),
        "json" | "jsonc" => Some(SyntaxLanguage::Json),
        "md" | "markdown" | "mdown" | "mkd" | "mdwn" => Some(SyntaxLanguage::Markdown),
        "txt" | "text" | "log" => Some(SyntaxLanguage::Txt),
        "mod" => Some(SyntaxLanguage::GoMod),
        "sum" => Some(SyntaxLanguage::GoSum),
        "css" | "scss" | "less" | "sass" | "qss" => Some(SyntaxLanguage::Css),
        "bat" | "cmd" => Some(SyntaxLanguage::Bat),
        "ps1" | "psm1" | "psd1" | "pssc" => Some(SyntaxLanguage::Ps1),
        "env" | "gitignore" | "dockerignore" | "hgignore" | "editorconfig"
        | "toml" | "ini" | "cfg" | "conf" => Some(SyntaxLanguage::Dotenv),
        _ => None,
    }
}